version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: srs
    ports:
      - '5432:5432'
    volumes:
      - ../volumes/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    volumes:
      - ../volumes/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

  srs:
    container_name: srs
    build:
      context: ../../
      dockerfile: Dockerfile
    env_file:
      - ../../.env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=root
      - DB_NAME=srs
      - PW_SALT=$2b$10$qrYTu8/afiBlJnQoFRk2D.
      - JWT_SECRET=WhLEtZX58zK9ql9fSMVSb7o9tt4uCsjB68XT6b05KB6v8kCyAaWxUeRnAfN0AxNE
    ports:
      - '5000:5000'
    depends_on:
      - postgres
