version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: srs
    ports:
      - '5432:5432'
    volumes:
      - ../volumes/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    volumes:
      - ../volumes/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:7.0-alpine
    ports:
      - '6379:6379'
    volumes:
      - ../volumes/redis:/data
    restart: unless-stopped

  # srs:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - DATABASE_URL=postgresql://admin:root@postgres:5432/srs
  #   ports:
  #     - '8000:8000'
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - postgres
