version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: srs
    ports:
      - '5432:5432'
    volumes:
      - ../volumes/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  srs-api:
    container_name: srs-api
    build:
      context: ../../
      dockerfile: Dockerfile
    env_file:
      - ../../.env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=root
      - DB_NAME=srs
      - JWT_SECRET=WhLEtZX58zK9ql9fSMVSb7o9tt4uCsjB68XT6b05KB6v8kCyAaWxUeRnAfN0AxNE
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    restart: unless-stopped

  srs-web:
    container_name: srs-web
    build:
      context: ../../../frontend/
      dockerfile: Dockerfile
    depends_on:
      - srs-api
    volumes:
      - ../../../frontend/src/etc/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - REACT_APP_API_URL=http://srs-api:5000
    ports:
      - '80:80'
    restart: unless-stopped

networks:
  network:
    driver: host
