services:
  postgres:
    type: database
    database: postgresql
    plan: free
    env:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: srs

  srs-api:
    type: web
    git: https://github.com/gustavoarendt/spaced-repetition-system/tree/main/api
    branch: main
    depends_on:
      - postgres
    env:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: root
      DB_NAME: srs
      JWT_SECRET: WhLEtZX58zK9ql9fSMVSb7o9tt4uCsjB68XT6b05KB6v8kCyAaWxUeRnAfN0AxNE

  srs-web:
    type: web
    git: https://github.com/gustavoarendt/spaced-repetition-system/tree/main/frontend
    branch: frontend
    depends_on:
      - srs-web

    env:
      REACT_APP_API_URL: http://srs-api:5000